language: "system_verilog"
seedFolders:
  - path: "kitten/test_data/system_verilog/slang"
    fileExtentions: [".sv", ".v"]

  - path: "kitten/test_data/system_verilog/Surelog"
    fileExtentions: [".sv", ".v"]

programsUnderTest:
  - command: "slang-afl"
    flagsToTest:
      - flags: []
    versionFlags:
      flags: ["--version"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.sysverilog.SlangCrashDetector"
