language: "JAVASCRIPT"
seedFolders:
  - path: "seeds"
    fileExtentions: [".js"]

programsUnderTest:
  # - command: "jerry-trunk-asan_ubsan"
  #   flagsToTest:
  #     - flags: []
  #   versionFlags:
  #     flags: ["--version"]
  #   crashDetectorClassName: "org.perses.fuzzer.compilers.javascript.JerryScriptCrashDetector"
  
  - command: "/Users/srinath/.jsvu/bin/v8"
    flagsToTest:
      - flags: []
    versionFlags:
      flags: ["--version"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.javascript.V8CrashDetector"
  
  - command: "/Users/srinath/.jsvu/bin/hermes"
    flagsToTest:
      - flags: []
    versionFlags:
      flags: ["--version"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.javascript.HermesCrashDetector"
  
  # - command: "/Users/srinath/.jsvu/bin/jsc"
  #   flagsToTest:
  #     - flags: []
  #   versionFlags:
  #     flags: ["--version"]
  #   crashDetectorClassName: "org.perses.fuzzer.compilers.javascript.JSCCrashDetector"
  
  - command: "/Users/srinath/.jsvu/bin/graaljs"
    flagsToTest:
      - flags: []
    versionFlags:
      flags: ["--version"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.javascript.GraalJSCrashDetector"
  
