language: "JAVASCRIPT"
seedFolders:
  - path: "kitten/scripts/javascript/seeds"
    fileExtentions: [".js"]

programsUnderTest:
  - command: "/Users/srinath/.jsvu/bin/v8"
    flagsToTest:
      - flags: []
    versionFlags:
      flags: ["--help"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.javascript.V8CrashDetector"
  
  - command: "/Users/srinath/.jsvu/bin/hermes"
    flagsToTest:
      - flags: []
    versionFlags:
      flags: ["--version"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.javascript.HermesCrashDetector"
  
  - command: "/Users/srinath/.jsvu/bin/graaljs"
    flagsToTest:
      - flags: []
    versionFlags:
      flags: ["--version"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.javascript.GraalJSCrashDetector" 