language: "JAVASCRIPT"
seedFolders:
  - path: "seeds"
    fileExtentions: [".js"]

programsUnderTest:
  # V8 Engine
  - command: "v8"
    flagsToTest:
      - flags: []
    versionFlags:
      flags: ["--help"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.javascript.V8CrashDetector"

  # XS Engine
  - command: "xs"
    flagsToTest:
      - flags: []
    versionFlags:
      flags: ["--version"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.javascript.XSCrashDetector"

  # QuickJS Engine
  - command: "quickjs"
    flagsToTest:
      - flags: []
    versionFlags:
      flags: ["--version"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.javascript.QuickJSCrashDetector"

  # JerryScript Engine
  - command: "jerryscript"
    flagsToTest:
      - flags: []
    versionFlags:
      flags: ["--version"]
    crashDetectorClassName: "org.perses.fuzzer.compilers.javascript.JerryScriptCrashDetector"
