#!/usr/bin/env python3
"""
ROBUST V8 source file instrumentation for allowlist tracking.
Handles edge cases and ensures safe insertion at global scope.
"""

import sys
import os
import re
import hashlib
from pathlib import Path

def generate_unique_marker_name(filepath):
    """Generate a unique variable name to avoid conflicts."""
    # Use hash of filepath to create unique but deterministic name
    path_hash = hashlib.md5(str(filepath).encode()).hexdigest()[:8]
    return f"__allowlist_marker_{path_hash}__"

def find_safe_insertion_point(content):
    """
    Find the safest point to insert code at global scope.
    Returns position after includes but before any code/declarations.
    """
    
    # Strategy: Find the last #include, then skip any blank lines/comments
    # to find the first line of actual code
    
    # Find all #include directives
    include_matches = list(re.finditer(r'^\s*#\s*include\s+[<"][^>"]+[>"]', content, re.MULTILINE))
    
    if include_matches:
        # Start after the last #include
        last_include = include_matches[-1]
        search_start = last_include.end()
    else:
        # No includes - skip license header
        # Find first non-comment, non-blank line
        lines = content.split('\n')
        search_start = 0
        for i, line in enumerate(lines):
            stripped = line.strip()
            # Skip empty lines, // comments, /* comments, and * continuation
            if stripped and not stripped.startswith('//') and not stripped.startswith('/*') and not stripped.startswith('*'):
                search_start = content.find(line)
                break
    
    # From search_start, find the next newline to insert after
    newline_pos = content.find('\n', search_start)
    if newline_pos == -1:
        return len(content)  # End of file
    
    # Skip any preprocessor directives (#define, #ifdef, etc.) after includes
    pos = newline_pos + 1
    while pos < len(content):
        # Find the next line
        line_start = pos
        line_end = content.find('\n', pos)
        if line_end == -1:
            line_end = len(content)
        
        line = content[line_start:line_end].strip()
        
        # If it's a preprocessor directive, skip it
        if line.startswith('#'):
            pos = line_end + 1
            continue
        
        # If it's blank or comment, skip it
        if not line or line.startswith('//') or line.startswith('/*') or line.startswith('*'):
            pos = line_end + 1
            continue
        
        # Found first line of actual code
        return line_start
    
    return pos

def is_safe_to_patch(content):
    """Check if file is safe to patch (not auto-generated, etc.)."""
    
    # Check for auto-generated markers
    autogen_markers = [
        'DO NOT EDIT',
        'AUTO-GENERATED',
        'AUTOGENERATED',
        'Generated by',
        'This file was generated',
    ]
    
    first_1000_chars = content[:1000].upper()
    for marker in autogen_markers:
        if marker.upper() in first_1000_chars:
            return False, f"File appears auto-generated (contains '{marker}')"
    
    return True, ""

def create_marker_code(filepath, v8_root, marker_var_name):
    """Create the instrumentation code."""
    
    try:
        rel_path = filepath.relative_to(v8_root)
    except:
        rel_path = filepath.name
    
    # Use a macro-style approach for maximum compatibility
    # This avoids namespace issues and is valid in more contexts
    marker_code = f'''
// ALLOWLIST_EXEC_MARKER - Auto-generated by patch_v8_allowlist.py
#ifndef ALLOWLIST_TRACKER_INCLUDED_{marker_var_name}
#define ALLOWLIST_TRACKER_INCLUDED_{marker_var_name}
#include "src/init/allowlist-tracker.h"
namespace {{ 
  [[maybe_unused]] static const bool {marker_var_name} = (v8::internal::MarkAllowlistFile("{rel_path}"), true);
}}
#endif  // ALLOWLIST_TRACKER_INCLUDED_{marker_var_name}
'''
    
    return marker_code

def add_marker_to_file(filepath, v8_root):
    """Add execution marker to a .cc file with extensive safety checks."""
    
    # Only patch .cc files
    if not str(filepath).endswith('.cc'):
        print(f"[SKIP] {filepath} (not a .cc file)", file=sys.stderr)
        return False
    
    try:
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
    except Exception as e:
        print(f"[SKIP] Cannot read {filepath}: {e}", file=sys.stderr)
        return False
    
    # Check if already patched
    if 'ALLOWLIST_EXEC_MARKER' in content:
        print(f"[SKIP] Already patched: {filepath}", file=sys.stderr)
        return False
    
    # Check if safe to patch
    is_safe, reason = is_safe_to_patch(content)
    if not is_safe:
        print(f"[SKIP] {filepath}: {reason}", file=sys.stderr)
        return False
    
    # Generate unique marker name
    marker_var_name = generate_unique_marker_name(filepath)
    
    # Find safe insertion point
    try:
        insert_pos = find_safe_insertion_point(content)
    except Exception as e:
        print(f"[SKIP] Cannot find insertion point in {filepath}: {e}", file=sys.stderr)
        return False
    
    # Create marker code
    marker_code = create_marker_code(filepath, v8_root, marker_var_name)
    
    # Insert marker
    new_content = content[:insert_pos] + marker_code + content[insert_pos:]
    
    # Sanity check: ensure we didn't break the file structure
    # Count braces before and after
    open_braces_before = content.count('{')
    close_braces_before = content.count('}')
    open_braces_after = new_content.count('{')
    close_braces_after = new_content.count('}')
    
    # We should have added exactly 1 open and 1 close brace
    if (open_braces_after - open_braces_before != 1 or 
        close_braces_after - close_braces_before != 1):
        print(f"[ERROR] Brace count mismatch in {filepath}, skipping", file=sys.stderr)
        return False
    
    try:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print(f"[PATCHED] {filepath}", file=sys.stderr)
        return True
    except Exception as e:
        print(f"[ERROR] Cannot write {filepath}: {e}", file=sys.stderr)
        return False


def create_allowlist_header(v8_root):
    """Create allowlist tracker header for execution tracking."""
    
    header_path = v8_root / 'src' / 'init' / 'allowlist-tracker.h'
    header_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Simple, robust implementation
    header_content = """// Auto-generated allowlist execution tracker
// DO NOT EDIT - Generated by patch_v8_allowlist.py

#ifndef V8_INIT_ALLOWLIST_TRACKER_H_
#define V8_INIT_ALLOWLIST_TRACKER_H_

#include <atomic>
#include <cstdio>

namespace v8 {
namespace internal {

// Global flag - set to true when any allowlisted file code is EXECUTED
inline std::atomic<bool> g_touched_allowlist{false};

// Mark that code from an allowlisted file was executed
// Returns true for convenience in static initialization
inline bool MarkAllowlistFile(const char* filename) {
  g_touched_allowlist.store(true, std::memory_order_relaxed);
  return true;
}

}  // namespace internal
}  // namespace v8

#endif  // V8_INIT_ALLOWLIST_TRACKER_H_
"""
    
    with open(header_path, 'w', encoding='utf-8') as f:
        f.write(header_content)
    
    print(f"[CREATED] {header_path}", file=sys.stderr)
    return True


def patch_d8_shell(v8_root):
    """Patch d8.cc to print ALLOWLIST_HIT on exit if flag is set."""
    
    d8_cc = v8_root / 'src' / 'd8' / 'd8.cc'
    if not d8_cc.exists():
        print(f"[WARN] d8.cc not found at {d8_cc}", file=sys.stderr)
        return False
    
    try:
        with open(d8_cc, 'r', encoding='utf-8') as f:
            content = f.read()
    except:
        return False
    
    if 'ALLOWLIST_EXIT_CHECK' in content:
        print("[SKIP] d8.cc already patched", file=sys.stderr)
        return True
    
    # Add include at the top
    if 'allowlist-tracker.h' not in content:
        include_match = re.search(r'^\s*#\s*include\s+[<"]', content, re.MULTILINE)
        if include_match:
            include_pos = content.find('\n', include_match.start())
            content = (content[:include_pos+1] + 
                      '#include "src/init/allowlist-tracker.h"\n' + 
                      content[include_pos+1:])
    
    # Find main function's final return statement
    main_match = re.search(r'int\s+main\s*\([^)]*\)\s*\{', content)
    if not main_match:
        print("[WARN] Cannot find main() in d8.cc", file=sys.stderr)
        return False
    
    main_start = main_match.end()
    
    # Find the last return statement in main
    remaining = content[main_start:]
    return_matches = list(re.finditer(r'\n(\s*)return\s+', remaining))
    
    if not return_matches:
        print("[WARN] Cannot find return in main()", file=sys.stderr)
        return False
    
    # Use the last return
    last_return = return_matches[-1]
    insert_pos = main_start + last_return.start() + 1
    indent = last_return.group(1)
    
    # Insert check before return
    check_code = f'''{indent}// ALLOWLIST_EXIT_CHECK
{indent}if (v8::internal::g_touched_allowlist.load(std::memory_order_relaxed)) {{
{indent}  fprintf(stderr, "ALLOWLIST_HIT\\n");
{indent}  fflush(stderr);
{indent}}}
'''
    
    new_content = content[:insert_pos] + check_code + content[insert_pos:]
    
    try:
        with open(d8_cc, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print("[PATCHED] d8.cc", file=sys.stderr)
        return True
    except Exception as e:
        print(f"[ERROR] Cannot patch d8.cc: {e}", file=sys.stderr)
        return False


def main():
    if len(sys.argv) < 3:
        print("Usage: patch_v8_allowlist.py <v8_root> <allowlist_file>", file=sys.stderr)
        sys.exit(1)
    
    v8_root = Path(sys.argv[1]).resolve()
    allowlist_file = Path(sys.argv[2]).resolve()
    
    if not v8_root.exists():
        print(f"ERROR: V8 root not found: {v8_root}", file=sys.stderr)
        sys.exit(1)
    
    if not allowlist_file.exists():
        print(f"ERROR: Allowlist file not found: {allowlist_file}", file=sys.stderr)
        sys.exit(1)
    
    print(f"[INFO] Patching V8 at: {v8_root}", file=sys.stderr)
    print(f"[INFO] Using allowlist: {allowlist_file}", file=sys.stderr)
    
    # Create header
    create_allowlist_header(v8_root)
    
    # Read allowlist
    with open(allowlist_file, 'r') as f:
        allowlist = [line.strip() for line in f if line.strip()]
    
    print(f"[INFO] Found {len(allowlist)} files in allowlist", file=sys.stderr)
    
    # Patch each .cc file
    patched_count = 0
    skipped_count = 0
    error_count = 0
    
    for rel_path in allowlist:
        file_path = v8_root / rel_path
        
        if not file_path.exists():
            print(f"[SKIP] File not found: {file_path}", file=sys.stderr)
            skipped_count += 1
            continue
        
        if file_path.suffix not in ['.cc', '.cpp']:
            skipped_count += 1
            continue
        
        result = add_marker_to_file(file_path, v8_root)
        if result:
            patched_count += 1
        else:
            if file_path.exists():
                skipped_count += 1
    
    # Patch d8
    patch_d8_shell(v8_root)
    
    print(f"\n[SUMMARY]", file=sys.stderr)
    print(f"  Patched: {patched_count} files", file=sys.stderr)
    print(f"  Skipped: {skipped_count} files", file=sys.stderr)
    print(f"[INFO] V8 instrumentation complete", file=sys.stderr)


if __name__ == '__main__':
    main()
